name: outline_pie_chart
description: "Create beautiful and customizable animated pie charts with support for RTL languages and segment gaps. Perfect for visually engaging data representation in Flutter apps."
version: 0.0.1
homepage: https://github.com/shervin-h/outline_pie_chart
repository: https://github.com/shervin-h/outline_pie_chart
issue_tracker: https://github.com/shervin-h/outline_pie_chart/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
